### PR TITLE
WIP: sql source to pyodbc

### PR DESCRIPTION
**Pull request by chollinger**
NOTE: Still have to change the CI/CD stuff to test different DB distros. Also have to make sure the tests actually do what they're supposed to.

  * Primary Contact: [Cory Hollinger](mailto:cory.hollinger@target.com)

### Purpose

Changing the SQL source to use pyodbc instead of psycopg2. This opens the list of available DB providers from one to many.

### Expected Outcome

Sourcing is possible from other DB providers (postgres, SQL Server, Oracle, MySQL, etc)
  
### Checklist
 - [x] Tests
 - [ ] Documentation
 - [ ] Maintainer Code Review

### CODE REVIEW

**Comment by gamagori** [comment]
@chollinger You want to take a peek at this sometime this week?

**Comment by chollinger** [comment]
@gamagori someone else is looking into this for now. After talking to Ron, I realized I was being dumb and needed to go a different route with the tests. It's actively being worked on.

**Comment by gamagori** [comment]
ｓｏｕｎｄｓ　ｌｉｋｅ　ａ　ｐｌａｎ　ｍｙ　ｍａｎ　ゖ悪扱園ェま. Let me know if I can do anything.

**Comment by chollinger** [comment]
Closing this. Will reopen if it ever becomes a thing again

**Pull request closed without merging**
